# IN LAB-1

# Suppose that you are given a small 3x2 matrix, you have to calculate Principal Component Analysis without using pca () function

In [1]:
import numpy as np
from sklearn.decomposition import PCA

# Given matrix
matrix = np.array([[3, 5], [4, 2], [1, 6]])

# Step 1.1: Mean Center the Data
mean_centered_matrix = matrix - np.mean(matrix, axis=0)

# Step 1.2: Calculate the Covariance Matrix
cov_matrix = np.cov(mean_centered_matrix, rowvar=False)

# Step 1.3: Compute the Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

# Step 1.4: Determine the Principal Components
# Sort eigenvalues and eigenvectors
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

# Principal Components (Manually Calculated)
principal_components_manual = eigenvectors

# Step 2: Calculate PCA using the PCA() function from scikit-learn
pca = PCA(n_components=2)
principal_components_sklearn = pca.fit_transform(matrix)

mean_centered_matrix, cov_matrix, eigenvalues, principal_components_manual, principal_components_sklearn


(array([[ 0.33333333,  0.66666667],
        [ 1.33333333, -2.33333333],
        [-1.66666667,  1.66666667]]),
 array([[ 2.33333333, -2.83333333],
        [-2.83333333,  4.33333333]]),
 array([6.3379594 , 0.32870727]),
 array([[ 0.57757246, -0.81633943],
        [-0.81633943, -0.57757246]]),
 array([[-0.35170213,  0.65716145],
        [ 2.6748886 , -0.25921649],
        [-2.32318647, -0.39794495]]))

# IN LAB-2

# Calculate the principal component analysis for the matrix given in Q1 using PCA

In [2]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Example data
data = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0]])

# Standardizing the data
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data)

# Applying PCA
pca = PCA(n_components=1)  # Reducing to 1 principal component for simplicity
data_pca = pca.fit_transform(data_scaled)

print("Original Data:\n", data)
print("Transformed Data:\n", data_pca)


Original Data:
 [[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]]
Transformed Data:
 [[-0.5124457 ]
 [ 2.57528445]
 [-0.69555387]
 [ 0.1485184 ]
 [-1.51580328]]
